version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_instance
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: